import Link from 'next/link'
import Head from 'next/head'

export default function Layout({children}){
    return( 
        <div>
            <Head>
                <title>CL RECORDS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <header>

                </header>

                {children}

                <footer>

                </footer>
            </div>  
        </div>
    );
}